### ISSUE TITLE
New sensor type for EV charging?

### ISSUE THREAD

**Issue by Extati** [woopstar/hsem#43]
Would it make sense to allow users to select a Boleen sensor instead of the sensor.xxx during the setup of EV Chargers?

This would make it easier to create a virtual sensor, allowing users to, for example, "turn on" their electric vehicle charger, and the integration would automatically ensure that the battery doesn't get drained.

It might also be possible to implement this in a simpler way, but many users today have Clever chargers, where unfortunately, it's not possible to access the charger status.

**Comment by woopstar** [comment]
I'm not entirely sure what you mean. Isn't this what the EV Charger Status Sensor input sensor does?

What you ask for is that you can only add a sensor right now. What you want to do is also to be able to add an input_boolean from a helper/template

**Comment by Extati** [comment]
> What you ask for is that you can only add a sensor right now. What you want to do is also to be able to add an input_boolean from a helper/template

Yes, correct - That would make it much easier for us whit an charger who can't easily be implemented in HA.

Sorry if I wasent clear.
